### ISSUE TITLE
Bug on last decimal when convert AIP to DMS14

### ISSUE THREAD

**Issue by tmmocha** [donatmarko/ivao-aipcoord#1]
Some last digit was error.

In app AIP Coord
150735.7N 1022135.3E = N015.07.35.006;E102.21.35.003;
It should actually be:
150735.7N 1022135.3E = N015.07.35.600;E102.21.35.300;

**Comment by Tatpolc** [comment]
In the AIP Coord:
150735.7N 1022135.3E = N015.07.35.006;E102.21.35.003;

It should actually be:
150735.7N 1022135.3E = N015.07.35.600;E102.21.35.300;

**Comment by tmmocha** [comment]
01507357N 10221353E

the program have all the wrong output
15.126391:102.359723
N015.07.35.006;E102.21.35.003;
